### ISSUE TITLE
[MAP] 앱 종료 후 실행 시 지도 위치 관련

### ISSUE THREAD

**Issue by seongjxn** [kit-kitHub/Facilities_Info-Frontend#22]
- 앱을 종료하고 다시 실행 시, 마지막 지도 위치가 아닌 임의의 default? 위치로 이동하게 되는 것 같음

- 현재 지도의 위치를 지속적으로 저장하고, 앱 종료 후 실행 시 해당 위치로 표시하는 로직에 문제가 있는 것 같다

**Comment by KangJiHyeock** [comment]
화면 종료할때 값을 Observer로 감지하여 저장하고 화면이 다시 켜질 때 그 값을 불러오도록 수정하여 이슈를 완료하였습니다
이와 관련하여 PR올리겠습니다 확인 부탁드립니다
