### ISSUE TITLE
[MAP] 핀치 줌인/줌아웃과 +- 버튼을 통한 줌인/줌아웃 연동 문제

### ISSUE THREAD

**Issue by seongjxn** [kit-kitHub/Facilities_Info-Frontend#23]
- 핀치 줌으로 지도 레벨을 조정한 것과, +- 버튼을 통해 지도 레벨을 조정했을 때 서로 레벨이 연동되지 않는 듯

- 핀치 줌아웃으로 지도를 작게 만들고, - 버튼을 누르면 지도가 더 작아지는 게 아닌, 다시 커지는 문제가 있음

**Comment by KangJiHyeock** [comment]
![image](https://github.com/user-attachments/assets/a42af12d-d718-436d-b4eb-a8429991e370)
이걸로 현재 zoom이 변경되는값을 저장하여 + - 로 핀치 줌 아웃이 공유되도록 만들었습니다
